steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/model-endpoint', '.']
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/model-endpoint']
  # Deploy the Docker image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'model-endpoint'
      - '--image'
      - 'gcr.io/$PROJECT_ID/model-endpoint'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-southeast2'
      - '--cpu=2'
      - '--memory=4Gi'
      - '--min-instances=1'
      - '--max-instances=10'
    # You can add additional options here, such as environment variables and service account permissions
